:ambulance: hotfix : auto sign-in after sign up
swsnu/swpp2020-team6 pull request #94
Opened 2020-11-30 06:58 UTC by yg-moon

- 동작 확인하였음.
- Testing Coverage 변동 없음.

진행내용
- sign-up page에서 onClickSignup 눌렀을 때 onSignup, onSignIn 한번에 진행하려니까, signIn action의 401 error 걸림. (아직 회원가입 안된 상태에서 sign In 시도)
- 그래서 sign-up action을 조금 수정함. dispatch signUpSuccess 다음에 signInSuccess 하게 해줌.
- (원래 response가 없는 상태여서 걱정했는데 다행히 백엔드에서 response를 sign-in 이랑 똑같이 주는듯)

혹시 변동되는 backend 사항 있으면 같이 고쳐야 할 듯.

2020-11-30 09:47 UTC, ddanddan18 commented
왜 401이 떴을까 ..? 어차피 post 보내서 뒤에다가 확인해야하는 건 똑같은데 ..? 
(sign up).then(sign in) 이렇게 했는데도 ..?

2020-11-30 09:54 UTC, yg-moon commented
> 왜 401이 떴을까 ..? 어차피 post 보내서 뒤에다가 확인해야하는 건 똑같은데 ..?
> (sign up).then(sign in) 이렇게 했는데도 ..?

그 actions 파일 말고 sign-up container 파일에서 처리했을 때 그렇게 된다는 거였음!
회원가입 되기 전에 로그인 요청 보내는거라 오류 나는게 맞는듯.

2020-11-30 11:52 UTC, gina7484 requested changes

2020-11-30 11:52 UTC, gina7484 commented on frontend/src/store/actions/user.js
>          dispatch(signUpSuccess_());
확인해보니까 signUpSuccess_가 signUp action을 dispatc하는데
user reducer들어가보면 signUp해도 {...state}를 return해서
결국 안해주는거랑 똑같아서

1.  signUpSuccess_ 함수 없애고
2. signUp action도 actionTypes랑 user reducer에서 없애줘도 될 것 같아.
3. 그리고 관련 testing이 많아봤자 한두개일 거 같은데 각자 없애주고.

2020-11-30 12:03 UTC, yg-moon commented on frontend/src/store/actions/user.js
>          dispatch(signUpSuccess_());
맞네... 그 전에는 아무것도 안 하는 액션으로서의 의미가 남아있긴 했는데
이제 합쳐버리면서 그렇게 줄일 수 있게 됐네.

그렇게 하면 더 깔끔할 듯! 그럼 그거까지 고친 다음 머지하겠습니다.

2020-12-01 10:27 UTC, yg-moon commented on frontend/src/store/actions/user.js
>          dispatch(signUpSuccess_());
변경사항 확인하면 머지 하겠습니다~
테스팅은 변동사항 없어서 안 고침.

2020-12-01 10:30 UTC, merged